<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>home</title>
</head>
<body>
    <h1>Apenas uma página de teste</h1>
    <?php if( $this->content['param'] ): ?> 
        Parâmetro: <?php echo $this->content['param']; ?>
    <?php endif; ?>
</body>
</html>